"""Fix Role desc and BulkJob tenant

Revision ID: 236e46602d0d
Revises: 4af76262e9c8
Create Date: 2026-01-17 08:59:54.900601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236e46602d0d'
down_revision: Union[str, Sequence[str], None] = '4af76262e9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulk_jobs', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bulk_jobs_tenant_id'), 'bulk_jobs', ['tenant_id'], unique=False)
    op.add_column('roles', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'description')
    op.drop_index(op.f('ix_bulk_jobs_tenant_id'), table_name='bulk_jobs')
    op.drop_column('bulk_jobs', 'tenant_id')
    # ### end Alembic commands ###
