"""Fix Audit Module

Revision ID: 29e9becf8d61
Revises: eb2ee6c01b03
Create Date: 2026-01-15 04:40:51.730769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29e9becf8d61'
down_revision: Union[str, Sequence[str], None] = 'eb2ee6c01b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('audit_logs', sa.Column('entity', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('changes', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('meta', sa.JSON(), nullable=True))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_audit_logs_request_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_target_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_target_type', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_column('audit_logs', 'state_before')
    op.drop_column('audit_logs', 'request_id')
    op.drop_column('audit_logs', 'target_id')
    op.drop_column('audit_logs', 'target_type')
    op.drop_column('audit_logs', 'state_after')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('state_after', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('target_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('state_before', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('ix_audit_logs_target_type', 'audit_logs', ['target_type'], unique=False)
    op.create_index('ix_audit_logs_target_id', 'audit_logs', ['target_id'], unique=False)
    op.create_index('ix_audit_logs_request_id', 'audit_logs', ['request_id'], unique=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('audit_logs', 'meta')
    op.drop_column('audit_logs', 'changes')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity')
    op.drop_column('audit_logs', 'tenant_id')
    # ### end Alembic commands ###
