"""fix_missing_columns

Revision ID: 37e613eac925
Revises: 236e46602d0d
Create Date: 2026-02-03 09:43:53.847266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '37e613eac925'
down_revision: Union[str, Sequence[str], None] = '236e46602d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_id', sa.Integer(), nullable=True))
    op.drop_index('ix_audit_logs_tenant_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['id'])
    op.drop_column('audit_logs', 'user_id')
    op.drop_column('audit_logs', 'tenant_id')
    op.create_index(op.f('ix_bulk_jobs_status'), 'bulk_jobs', ['status'], unique=False)
    op.alter_column('bulk_messages', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_bulk_messages_status'), 'bulk_messages', ['status'], unique=False)
    op.create_index(op.f('ix_bulk_messages_to_number'), 'bulk_messages', ['to_number'], unique=False)
    op.create_index(op.f('ix_bulk_messages_whatsapp_message_id'), 'bulk_messages', ['whatsapp_message_id'], unique=False)
    op.drop_constraint('bulk_messages_job_id_fkey', 'bulk_messages', type_='foreignkey')
    op.create_foreign_key(None, 'bulk_messages', 'bulk_jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.add_column('chat_messages', sa.Column('message_type', sa.String(), nullable=True))
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.drop_index('ix_contacts_phone', table_name='contacts')
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.create_unique_constraint('uq_contact_tenant_email', 'contacts', ['tenant_id', 'email'])
    op.create_unique_constraint('uq_contact_tenant_phone', 'contacts', ['tenant_id', 'phone'])
    op.alter_column('message_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1024),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    op.drop_constraint('message_embeddings_message_id_fkey', 'message_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'message_embeddings', 'chat_messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_message_status_id'), 'message_status', ['id'], unique=False)
    op.drop_constraint('message_status_message_id_fkey', 'message_status', type_='foreignkey')
    op.create_foreign_key(None, 'message_status', 'chat_messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_reply_suggestions_id'), 'reply_suggestions', ['id'], unique=False)
    op.drop_constraint('reply_suggestions_message_id_fkey', 'reply_suggestions', type_='foreignkey')
    op.create_foreign_key(None, 'reply_suggestions', 'chat_messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.add_column('roles', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_role_tenant_name', 'roles', ['tenant_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_tenant_name', 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_column('roles', 'tenant_id')
    op.drop_constraint(None, 'reply_suggestions', type_='foreignkey')
    op.create_foreign_key('reply_suggestions_message_id_fkey', 'reply_suggestions', 'chat_messages', ['message_id'], ['id'])
    op.drop_index(op.f('ix_reply_suggestions_id'), table_name='reply_suggestions')
    op.drop_constraint(None, 'message_status', type_='foreignkey')
    op.create_foreign_key('message_status_message_id_fkey', 'message_status', 'chat_messages', ['message_id'], ['id'])
    op.drop_index(op.f('ix_message_status_id'), table_name='message_status')
    op.drop_constraint(None, 'message_embeddings', type_='foreignkey')
    op.create_foreign_key('message_embeddings_message_id_fkey', 'message_embeddings', 'chat_messages', ['message_id'], ['id'])
    op.alter_column('message_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=1024),
               existing_nullable=True)
    op.drop_constraint('uq_contact_tenant_phone', 'contacts', type_='unique')
    op.drop_constraint('uq_contact_tenant_email', 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.create_index('ix_contacts_phone', 'contacts', ['phone'], unique=True)
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=True)
    op.drop_column('chat_messages', 'message_type')
    op.drop_constraint(None, 'bulk_messages', type_='foreignkey')
    op.create_foreign_key('bulk_messages_job_id_fkey', 'bulk_messages', 'bulk_jobs', ['job_id'], ['id'])
    op.drop_index(op.f('ix_bulk_messages_whatsapp_message_id'), table_name='bulk_messages')
    op.drop_index(op.f('ix_bulk_messages_to_number'), table_name='bulk_messages')
    op.drop_index(op.f('ix_bulk_messages_status'), table_name='bulk_messages')
    op.alter_column('bulk_messages', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_bulk_jobs_status'), table_name='bulk_jobs')
    op.add_column('audit_logs', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
    op.drop_column('audit_logs', 'actor_id')
    # ### end Alembic commands ###
