"""Add Inventory and RBAC

Revision ID: 6d8e36d42758
Revises: 29e9becf8d61
Create Date: 2026-01-15 08:53:50.124795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d8e36d42758'
down_revision: Union[str, Sequence[str], None] = '29e9becf8d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.drop_column('products', 'stock_level')
    op.add_column('stock_transactions', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('stock_transactions', sa.Column('qty_change', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_stock_transactions_product_id'), 'stock_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_transactions_tenant_id'), 'stock_transactions', ['tenant_id'], unique=False)
    op.drop_column('stock_transactions', 'change_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transactions', sa.Column('change_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_stock_transactions_tenant_id'), table_name='stock_transactions')
    op.drop_index(op.f('ix_stock_transactions_product_id'), table_name='stock_transactions')
    op.drop_column('stock_transactions', 'qty_change')
    op.drop_column('stock_transactions', 'tenant_id')
    op.add_column('products', sa.Column('stock_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
