"""Add bulk_jobs and bulk_messages tables

Revision ID: f59a22dfbbcd
Revises: 156044845445
Create Date: 2025-11-05 11:27:25.352879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59a22dfbbcd'
down_revision: Union[str, Sequence[str], None] = '156044845445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('to_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['bulk_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_messages_job_id'), 'bulk_messages', ['job_id'], unique=False)
    op.create_index(op.f('ix_bulk_messages_to_number'), 'bulk_messages', ['to_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bulk_messages_to_number'), table_name='bulk_messages')
    op.drop_index(op.f('ix_bulk_messages_job_id'), table_name='bulk_messages')
    op.drop_table('bulk_messages')
    op.drop_table('bulk_jobs')
    # ### end Alembic commands ###
