"""conversations + chat messages

Revision ID: f65604e27b22
Revises: 64193863c50a
Create Date: 2025-11-19 16:23:26.415047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65604e27b22'
down_revision: Union[str, Sequence[str], None] = '64193863c50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_customer_number'), 'conversations', ['customer_number'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('from_number', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_conversations_customer_number'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
