"""add contact_id FK to messages

Revision ID: 1a32cfca7d7e
Revises: c871b8a1bf57
Create Date: 2025-09-14 07:25:28.358160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a32cfca7d7e'
down_revision: Union[str, Sequence[str], None] = 'c871b8a1bf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'contact_id')
    # ### end Alembic commands ###
