"""messages table update

Revision ID: d960c6987c7c
Revises: 1a32cfca7d7e
Create Date: 2025-09-14 10:32:15.136696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd960c6987c7c'
down_revision: Union[str, Sequence[str], None] = '1a32cfca7d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('from_number', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('to_number', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('message_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('payload', sa.JSON(), nullable=True))
    op.add_column('messages', sa.Column('text', sa.Text(), nullable=True))
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_messages_from_number'), 'messages', ['from_number'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_messages_to_number'), 'messages', ['to_number'], unique=False)
    op.drop_column('messages', 'sender')
    op.drop_column('messages', 'message_body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_body', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_messages_to_number'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_number'), table_name='messages')
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('messages', 'text')
    op.drop_column('messages', 'payload')
    op.drop_column('messages', 'message_id')
    op.drop_column('messages', 'to_number')
    op.drop_column('messages', 'from_number')
    # ### end Alembic commands ###
